name: CI

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - main

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['swift:5.2', 'swift:5.3', 'swift:5.4']
    container:
      image: ${{ matrix.tag }}
    steps:
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
