# run this with docker-compose -f docker/docker-compose.yml run test
version: "3.3"

services:
  common: &common
    build: .
    volumes:
      - ..:/working
    working_dir: /working

  test:
    <<: *common
    build: .
    volumes:
      - ..:/working
    working_dir: /working
    depends_on:
      - localstack
    environment:
      - APIGATEWAY_ENDPOINT=http://localstack:4567
      - DYNAMODB_ENDPOINT=http://localstack:4569
      - IAM_ENDPOINT=http://localstack:4593
      - S3_ENDPOINT=http://localstack:4572
      - SNS_ENDPOINT=http://localstack:4575
      - SQS_ENDPOINT=http://localstack:4576
      - SSM_ENDPOINT=http://localstack:4583
      - STS_ENDPOINT=http://localstack:4592
    command: /bin/bash -xcl "swift test"

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=apigateway,dynamodb,iam,s3,sns,sqs,ssm,sts
    volumes:
      - "/tmp/localstack:/tmp/localstack"

  shell:
    <<: *common
    entrypoint: /bin/bash
