sourcekitten_sourcefile:
  - sourcekitten/AWSSDKSwiftCore.json
{%for service in services %}
  - sourcekitten/{{service}}.json
{%endfor %}

author: Yuki Takei, Joe Smith, Jonathan McAllister, Adam Fowler
author_url: https://github.com/swift-aws
github_url: https://github.com/swift-aws/aws-sdk-swift
copyright: '© Copyright (c) 2020 Yuki Takei(noppoMan), Joe Smith(Yasumoto), Jonathan McAllister(jonnymacs), Adam Fowler(adam-fowler), Fabian Fett(fabianfett)'
readme: README.md

custom_categories:
  - name: AWSSDKSwiftCore
    children:
      - AWSClient
      - AWSShape
      - AWSDecodableShape
      - AWSEncodableShape
      - AWSShapeWithPayload
      - AWSPayload
      - AWSRequest
      - AWSResponse
      - AWSErrorType
      - AWSServiceMiddleware
      - AWSLoggingMiddleware
      - Region
      - XML
{% for service in services %}
  - name: {{service}}
    children:
      - {{service}}
      - {{service}}ErrorType
{%endfor %}
