name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['nightly-bionic', 'nightly-focal', 'nightly-centos8', 'nightly-amazonlinux2']
    services:
      localstack:
        image: localstack/localstack
        options: >-
          --workdir /opt/code/localstack/
    container:
      image: swiftlang/swift:${{ matrix.tag }}
      env:
        APIGATEWAY_ENDPOINT : "http://localstack:4566"
        DYNAMODB_ENDPOINT   : "http://localstack:4566"
        IAM_ENDPOINT        : "http://localstack:4566"
        S3_ENDPOINT         : "http://localstack:4566"
        SNS_ENDPOINT        : "http://localstack:4566"
        SQS_ENDPOINT        : "http://localstack:4566"
        SSM_ENDPOINT        : "http://localstack:4566"
        STS_ENDPOINT        : "http://localstack:4566"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.tag == 'nightly-bionic' || matrix.tag == 'nightly-focal'}}
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata zlib1g-dev
    - name: Install dependencies (Amazon Linux2/CentOS8)
      if: ${{ matrix.tag == 'nightly-amazonlinux2' || matrix.tag == 'nightly-centos8'}}
      run: |
        yum -y update
        yum -y install zlib-devel
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
